# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-18 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantfilesmodel',
            old_name='alevel_certificate',
            new_name='alevelcertificate',
        ),
        migrations.RenameField(
            model_name='importantfilesmodel',
            old_name='bachelor_certificate',
            new_name='bachelorcertificate',
        ),
        migrations.RenameField(
            model_name='importantfilesmodel',
            old_name='bachelor_transcript',
            new_name='bachelortranscript',
        ),
        migrations.RenameField(
            model_name='importantfilesmodel',
            old_name='clinical_record',
            new_name='clinicalrecord',
        ),
        migrations.RenameField(
            model_name='importantfilesmodel',
            old_name='medical_examination',
            new_name='medicalexamination',
        ),
        migrations.RenameField(
            model_name='importantfilesmodel',
            old_name='olevel_certificate',
            new_name='olevelcertificate',
        ),
    ]
