# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-20 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180818_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed', models.CharField(max_length=120, null=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
