# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20190108_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Country_issue',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Date_of_birth',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Degree_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Family_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Field',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='First_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Highest_degree',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Pasport_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Place_of_Birth',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Religion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Second_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='Valid_until',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='occupation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='whats_app',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
