# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-08 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20190108_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfomodel',
            name='picture',
        ),
    ]
