# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-09 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_personalinfomodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfomodel',
            name='Age',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='personalinfomodel',
            name='Distric',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
