# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-09 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20190109_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfomodel',
            name='Region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
