# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_personalinfomodel_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomodationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('Gender', models.CharField(blank=True, max_length=120, null=True)),
                ('Number_of_persons', models.CharField(blank=True, max_length=120, null=True)),
                ('Country_of_residence', models.CharField(blank=True, max_length=120, null=True)),
                ('Hotels_name', models.CharField(blank=True, max_length=120, null=True)),
                ('Place', models.CharField(blank=True, max_length=120, null=True)),
                ('Double_or_single', models.CharField(blank=True, max_length=120, null=True)),
                ('Trip_advisor', models.CharField(blank=True, max_length=120, null=True)),
                ('Arrival_date', models.CharField(blank=True, max_length=120, null=True)),
                ('Arrival_address', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.CharField(blank=True, max_length=120, null=True)),
                ('Email', models.CharField(blank=True, max_length=120, null=True)),
                ('Emergence_phone', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirportPickUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('Gender', models.CharField(blank=True, max_length=120, null=True)),
                ('Number_of_persons', models.CharField(blank=True, max_length=120, null=True)),
                ('Country_of_residence', models.CharField(blank=True, max_length=120, null=True)),
                ('Flight_No', models.CharField(blank=True, max_length=120, null=True)),
                ('Depature_airport', models.CharField(blank=True, max_length=120, null=True)),
                ('Arival_city', models.CharField(blank=True, max_length=120, null=True)),
                ('Arrival_airport', models.CharField(blank=True, max_length=120, null=True)),
                ('Arrival_date', models.CharField(blank=True, max_length=120, null=True)),
                ('Arrival_address', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.CharField(blank=True, max_length=120, null=True)),
                ('Email', models.CharField(blank=True, max_length=120, null=True)),
                ('Emergence_phone', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
